ruby '2.3.1'
source 'https://rubygems.org'

gem 'lita'
gem 'lita-slack', github: 'litaio/lita-slack', branch: 'master'
gem 'lita-applause'
gem 'lita-poll'
gem 'lita-team'
gem 'lita-tell', github: 'charly-palencia/lita-tell', branch: 'master'
gem 'lita-team-balance', github: 'horozco/lita-team-balance', branch: 'master'
gem 'lita-slack-reactions', github: 'EdgarOrtegaRamirez/lita-slack-reactions', branch: 'master'
gem 'lita-service', github: 'equintana/lita-service', branch: 'master'
