ruby '2.3.0'
source 'https://rubygems.org'

gem 'lita'
gem 'lita-slack'
gem 'lita-applause'
gem 'lita-poll'
gem 'lita-team'
gem 'lita-tell', github: 'charly-palencia/lita-tell', branch: 'master'
gem 'lita-team-balance', github: 'horozco/lita-team-balance', branch: 'master'
